name: Build
on: [push, workflow_dispatch, repository_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install
        working-directory: ./kep
      - run: npm run build
        working-directory: ./kep
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "./kep/dist/index.bundle.user.js"
          token: ${{ secrets.GITHUB_TOKEN }}